sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t ianwhite/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true ianwhite/docker-react npm run test